#!/bin/bash

SRC=$1
DST=$2

usage() {
  echo "usage: ./gen_hal.sh <source hal file> <target boot cfg file>"
}

if [ "x$SRC" = "x" ] ; then
  usage
  exit -1
fi

if [ "x$DST" = "x" ] ; then
  usage
  exit -1
fi

echo "# Generated by gen_hal.sh" > $DST
echo "emc2_conf_hal_halfile_num=1" >> $DST
echo "emc2_conf_hal_halfile_0=ezcnc.hal" >> $DST

COUNT=1

while read LINE
do
  echo $LINE
  if [ "x$LINE" = "x" ] ; then
    echo "LINE is empty."
    echo "" >> $DST
    continue;
  fi
  FIRST_CHAR=${LINE:0:1}
  if [ $FIRST_CHAR = "#" ] ; then
    echo "it's a comment"
  else
    echo "# $LINE" >> $DST
    echo "emc2_conf_hal_halfile_0.$COUNT=$LINE" >> $DST
    let "COUNT=$COUNT + 1"
  fi
done < $SRC

